site_name: vessel-express
site_description: A simple plugin to use with napari
site_author: lennart kowitz

theme: readthedocs


repo_url: https://github.com/MMV-Lab/vessel-express

pages:
- Home: index.md
